#cmakedefine PROJECT_NAME "@PROJECT_NAME@"
#cmakedefine PROJECT_TARNAME "@PROJECT_TARNAME@"
#cmakedefine WAD_DATA "@WAD_DATA@"
#cmakedefine PROJECT_VERSION "@PROJECT_VERSION@"
#cmakedefine PROJECT_STRING "@PROJECT_STRING@"
#cmakedefine PROJECT_DEMO_STRING "@PROJECT_DEMO_STRING@"

#cmakedefine DOOMWADDIR "@DOOMWADDIR@"
#cmakedefine NYAN_ABSOLUTE_PWAD_PATH "@NYAN_ABSOLUTE_PWAD_PATH@"
#cmakedefine NYAN_NIGHTLY

#cmakedefine WORDS_BIGENDIAN

#cmakedefine HAVE_GETOPT
#cmakedefine HAVE_MMAP
#cmakedefine HAVE_CREATE_FILE_MAPPING
#cmakedefine HAVE_STRSIGNAL
#cmakedefine HAVE_MKSTEMP
#cmakedefine HAVE_GETPWUID

#cmakedefine HAVE_SYS_WAIT_H
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_ASM_BYTEORDER_H
#cmakedefine HAVE_DIRENT_H

#cmakedefine HAVE_LIBMAD
#cmakedefine HAVE_LIBFLUIDSYNTH
#cmakedefine HAVE_LIBXMP
#cmakedefine HAVE_LIBVORBISFILE
#cmakedefine HAVE_LIBPORTMIDI
#cmakedefine HAVE_LIBSPNG
#cmakedefine HAVE_DISCORD_RPC
#cmakedefine HAVE_SNDFILE_MPEG

#cmakedefine SIMPLECHECKS

#cmakedefine RANGECHECK
